# Site settings
title: Christine Ford
subtitle: Novelist, Poet, Teacher
email: christineford53@gmail.com
description: >
 Christine Ford is a published children's book author, advocate for adult literacy, and an extraodinary teacher.  A woman of many talents; she currently resides in Yangju, South Korea teaching.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# defaults
# keep_files: .git // causes unspecified error when serving page
# Build settings
safe: true
highlighter: pygments

exclude: 
    - christineford.sublime-project
    - christineford.sublime-workspace
    - .gitignore

markdown: rdiscount

lang: en
