# Site settings
title: Christine Ford
subtitle: Novelist, Poet, Teacher
email: christineford53@gmail.com
description: >
 Christine Ford is a published children's book author, advocate for adult literacy, and an extraodinary teacher.  A woman of many talents; she currently resides in Yangju, South Korea teaching.
baseurl: "/christineford.org" # the subpath of your site, e.g. /blog/
url: "djfordz.github.io" # the base hostname & protocol for your site

# defaults

# Build settings
highlighter: pygments

markdown: rdiscount

lang: en
